---
#MIT License
#
#Copyright (c) 2021 Pierre Michel Joubert
#
#Permission is hereby granted, free of charge, to any person obtaining a copy
#of this software and associated documentation files (the "Software"), to deal
#in the Software without restriction, including without limitation the rights
#to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
#copies of the Software, and to permit persons to whom the Software is
#furnished to do so, subject to the following conditions:
#
#The above copyright notice and this permission notice shall be included in all
#copies or substantial portions of the Software.
#
#THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
#IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
#FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
#AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
#LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
#OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
#SOFTWARE.
title: "rarefaction_per_tech_rep"
output: html_document
---

```{r}
library(data.table)
library(ggplot2)
library(scales)
library(dplyr)
```

```{r}

## read in df

df_rarefaction <- data.frame(fread('rarefaction_table'))

colnames(df_rarefaction) <- c('sample', 'percent_reads', 'read_count', 'ecc_count')

biorep_column <- c(rep(c('Bio Rep 1', 'Bio Rep 2'), each = 30), rep('Bio Rep 3', each = 20))

techrep_column <- c(rep('A',10), rep('B',10), rep('C',10),
                    rep('A',10), rep('B',10), rep('C',10),
                    rep('A',10), rep('B',10))

df_rarefaction$biorep <- biorep_column

df_rarefaction$techrep <- techrep_column


```

```{r}

p <- ggplot(df_rarefaction, aes(x = read_count, y = ecc_count, shape = biorep)) + geom_point() + geom_line(aes(color=techrep), lwd=0.25) + 
  labs(x="Mapped Reads",
       y="EccDNA Forming Regions") + theme(legend.title = element_blank()) +
  scale_x_continuous(breaks = c(25000000, 50000000, 75000000), labels = c('25,000,000', '50,000,000', '75,000,000')) +
  scale_y_continuous(breaks = c(50000, 100000, 150000, 200000), labels = c('50,000', '100,000', '150,000', '200,000'))+
  scale_color_manual(values = c('black', 'black', 'black'), guide='none')+theme(axis.text=element_text(size=6), axis.title=element_text(size=8), legend.text=element_text(size=8))

p

ggsave('rarefaction_by_sample.pdf', plot = p, width = 6.5, height = 4)


```

