---
#MIT License
#
#Copyright (c) 2021 Pierre Michel Joubert
#
#Permission is hereby granted, free of charge, to any person obtaining a copy
#of this software and associated documentation files (the "Software"), to deal
#in the Software without restriction, including without limitation the rights
#to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
#copies of the Software, and to permit persons to whom the Software is
#furnished to do so, subject to the following conditions:
#
#The above copyright notice and this permission notice shall be included in all
#copies or substantial portions of the Software.
#
#THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
#IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
#FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
#AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
#LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
#OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
#SOFTWARE.
title: "histone_marks_characteristics"
output: html_document
---

```{r}
library(data.table)
library(ggplot2)
```

```{r}

# define consistent colors
gg_color_hue <- function(n) {
  hues = seq(15, 375, length = n + 1)
  hcl(h = hues, l = 65, c = 100)[1:n]
}


colors <- gg_color_hue(10)

names(colors) <- c("Genome baseline", "All genes", "LTR TEs", "Methylated genes", "Nonmethylated genes",
                                            "Acetylated genes", "Nonacetylated genes",
                                            "Large eccDNAs", "LTR-eccDNAs", "MicroDNAs")
```



```{r}
# read in tab output from plot profile

df_read <- t(data.frame(fread("gc.tab")))

## need to do a lot of rearranging to get it into a format that works for ggplot
df <- data.frame( bin=as.vector(df_read[3:nrow(df_read),1]),
                  val=c(df_read[3:nrow(df_read),2], df_read[3:nrow(df_read),3], df_read[3:nrow(df_read),4], df_read[3:nrow(df_read),5],
                        df_read[3:nrow(df_read),6], df_read[3:nrow(df_read),7]),
                  label=c(rep('Genome baseline',160), rep('All genes',160), rep('LTR TEs',160), rep('Large eccDNAs',160),
                          rep('MicroDNAs',160), rep('LTR-eccDNAs',160)))

df$bin <- as.numeric(as.character(df$bin))
df$val <- as.numeric(as.character(df$val))


df$label <- factor(df$label, levels = c("Genome baseline", "All genes", "LTR TEs", "Methylated genes", "Nonmethylated genes",
                                            "Acetylated genes", "Nonacetylated genes",
                                            "Large eccDNAs", "LTR-eccDNAs", "MicroDNAs"))


subset_colors <- colors[names(colors) %in% df$label]

# plot gc content across tracks

p <- ggplot(df, aes(x=bin, y=val, group=label)) + geom_line(aes(color=label), lwd=0.5) + theme_classic() +
  scale_x_continuous(labels=c('-0.3kb', 'Start', 'End', '0.3kb'), breaks=c(1,30,130,160)) + xlab('')+theme(axis.text=element_text(size=6), axis.title=element_text(size=8), legend.title=element_blank(), legend.text=element_text(size=8)) + ylab('GC content')  +
  scale_colour_manual(values=subset_colors) +
  guides(color=guide_legend(nrow=3,byrow=TRUE,keywidth=0.1, keyheight=0.1, default.unit='inch')) +
  theme(legend.position = 'bottom', legend.box.margin =margin(-15,-10,0,-10))


p

ggsave('characteristics_gc.pdf', plot=p, width=3.25, height=2)

```

```{r}
df_read <- t(data.frame(fread("H3K27me3_1.tab")))

## need to do a lot of rearranging to get it into a format that works for ggplot

df <- data.frame( bin=as.vector(df_read[3:nrow(df_read),1]),
                  val=c(df_read[3:nrow(df_read),2], df_read[3:nrow(df_read),3], df_read[3:nrow(df_read),4], 
                        df_read[3:nrow(df_read),5], df_read[3:nrow(df_read),6], df_read[3:nrow(df_read),7],
                        df_read[3:nrow(df_read),8], df_read[3:nrow(df_read),9]),
                  label=c(rep('Genome baseline',160), rep('All genes',160), rep('LTR TEs',160), rep('Large eccDNAs',160),
                          rep('MicroDNAs',160), rep('LTR-eccDNAs',160),
                          rep('Methylated genes',160), rep('Nonmethylated genes',160)))

df$bin <- as.numeric(as.character(df$bin))
df$val <- as.numeric(as.character(df$val))

df$label <- factor(df$label, levels = c("Genome baseline", "All genes", "LTR TEs", "Methylated genes", "Nonmethylated genes",
                                            "Acetylated genes", "Nonacetylated genes",
                                            "Large eccDNAs", "LTR-eccDNAs", "MicroDNAs"))

subset_colors <- colors[names(colors) %in% df$label]

# ratio of H3K27me across tracks

p <- ggplot(df, aes(x=bin, y=val, group=label)) + geom_line(aes(color=label), lwd=0.5) + theme_classic() +
  scale_x_continuous(labels=c('-0.3kb', 'Start', 'End', '0.3kb'), breaks=c(1,30,130,160)) + xlab('')+theme(axis.text=element_text(size=6), axis.title=element_text(size=8), legend.title=element_blank(), legend.text=element_text(size=8)) + ylab('H3K27me3')  +
    scale_colour_manual(values=subset_colors) +
  guides(color=guide_legend(nrow=4,byrow=TRUE,keywidth=0.1, keyheight=0.1, default.unit='inch')) +
  theme(legend.position = 'bottom', legend.box.margin =margin(-15,-10,0,-10))


p

ggsave('characteristics_h3k27me3.pdf', plot=p, width=3.25, height=2)

```

```{r}
df_read <- t(data.frame(fread("H3K36me3_1.tab")))

## need to do a lot of rearranging to get it into a format that works for ggplot

df <- data.frame( bin=as.vector(df_read[3:nrow(df_read),1]),
                  val=c(df_read[3:nrow(df_read),2], df_read[3:nrow(df_read),3], df_read[3:nrow(df_read),4], df_read[3:nrow(df_read),5],
                        df_read[3:nrow(df_read),6], df_read[3:nrow(df_read),7]),
                  label=c(rep('Genome baseline',160), rep('All genes',160), rep('LTR TEs',160), rep('Large eccDNAs',160),
                          rep('MicroDNAs',160), rep('LTR-eccDNAs',160)))

df$bin <- as.numeric(as.character(df$bin))
df$val <- as.numeric(as.character(df$val))

df$label <- factor(df$label, levels = c("Genome baseline", "All genes", "LTR TEs", "Methylated genes", "Nonmethylated genes",
                                            "Acetylated genes", "Nonacetylated genes",
                                            "Large eccDNAs", "LTR-eccDNAs", "MicroDNAs"))

subset_colors <- colors[names(colors) %in% df$label]

# ratio of H3K36me across tracks

p <- ggplot(df, aes(x=bin, y=val, group=label)) + geom_line(aes(color=label), lwd=0.5) + theme_classic() +
  scale_x_continuous(labels=c('-0.3kb', 'Start', 'End', '0.3kb'), breaks=c(1,30,130,160)) + xlab('')+theme(axis.text=element_text(size=6), axis.title=element_text(size=8), legend.title=element_blank(), legend.text=element_text(size=8)) + ylab('H3K36me3')  +
    scale_colour_manual(values=subset_colors) +
  guides(color=guide_legend(nrow=3,byrow=TRUE,keywidth=0.1, keyheight=0.1, default.unit='inch')) +
  theme(legend.position = 'bottom', legend.box.margin =margin(-15,-10,0,-10))

p

ggsave('characteristics_h3k36me3.pdf', plot=p, width=3.25, height=2)
```

```{r}
df_read <- t(data.frame(fread("H3K27ac_1.tab")))

## need to do a lot of rearranging to get it into a format that works for ggplot

df <- data.frame( bin=as.vector(df_read[3:nrow(df_read),1]),
                  val=c(df_read[3:nrow(df_read),2], df_read[3:nrow(df_read),3], df_read[3:nrow(df_read),4], 
                        df_read[3:nrow(df_read),5], df_read[3:nrow(df_read),6], df_read[3:nrow(df_read),7],
                        df_read[3:nrow(df_read),8], df_read[3:nrow(df_read),9]),
                  label=c(rep('Genome baseline',160), rep('All genes',160), rep('LTR TEs',160), rep('Large eccDNAs',160),
                          rep('MicroDNAs',160), rep('LTR-eccDNAs',160),
                          rep('Acetylated genes',160), rep('Nonacetylated genes',160)))

df$bin <- as.numeric(as.character(df$bin))
df$val <- as.numeric(as.character(df$val))

df$label <- factor(df$label, levels = c("Genome baseline", "All genes", "LTR TEs", "Methylated genes", "Nonmethylated genes",
                                            "Acetylated genes", "Nonacetylated genes",
                                            "Large eccDNAs", "LTR-eccDNAs", "MicroDNAs"))

subset_colors <- colors[names(colors) %in% df$label]

# ratio of H3K27ac across tracks

p <- ggplot(df, aes(x=bin, y=val, group=label)) + geom_line(aes(color=label), lwd=0.5) + theme_classic() +
  scale_x_continuous(labels=c('-0.3kb', 'Start', 'End', '0.3kb'), breaks=c(1,30,130,160)) + xlab('')+theme(axis.text=element_text(size=6), axis.title=element_text(size=8), legend.title=element_blank(), legend.text=element_text(size=8)) + ylab('H3K27ac')  +
    scale_colour_manual(values=subset_colors) +
  guides(color=guide_legend(nrow=4,byrow=TRUE,keywidth=0.1, keyheight=0.1, default.unit='inch')) +
  theme(legend.position = 'bottom', legend.box.margin =margin(-15,-10,0,-10))


p

ggsave('characteristics_h3k27ac.pdf', plot=p, width=3.25, height=2)
```

