---
#MIT License
#
#Copyright (c) 2021 Pierre Michel Joubert
#
#Permission is hereby granted, free of charge, to any person obtaining a copy
#of this software and associated documentation files (the "Software"), to deal
#in the Software without restriction, including without limitation the rights
#to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
#copies of the Software, and to permit persons to whom the Software is
#furnished to do so, subject to the following conditions:
#
#The above copyright notice and this permission notice shall be included in all
#copies or substantial portions of the Software.
#
#THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
#IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
#FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
#AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
#LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
#OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
#SOFTWARE.
title: "table_making"
output: html_document
---

```{r}
library(gt)
```

```{r}

## WGS false positive table

df <- data.frame(t(data.frame(c(55248286, 12, 195, 195/55248286*1000000),
                 c(92346262, 8, 81, 81/92346262*1000000),
                 c(39133840, 5, 66, 66/39133840*1000000))))

# fix sigfigs
sigfigs <- function(x) {
  sigfig <- formatC(signif(x,digits=4), digits=4,format="fg", flag="#")
 return(sigfig)
}

df[] <- lapply(df, sigfigs)

colnames(df) <- c('Read count','EccDNA forming regions', 'Junction split reads', 'False positives per million reads')

df$rownames <- c('ERR2660591', 'SRR16282278', 'SRR11528297')

## just table formatting

gt <- gt(df, rowname_col = 'rownames')

gt <- cols_width(gt, everything() ~ px(150))

gt <- tab_stubhead(gt, 'Accessions')

gt <- cols_align(gt, align = 'center')



gtsave(gt, 'ecc_caller_on_wgs_data.png')

```

```{r}

## info directly from methods sections of these papers

df <- data.frame(t(data.frame(c('Plasmid Mini AX (A&A Biotechnology)','Plasmid Mini AX (A&A Biotechnology)',
                                'Plasmid-Safe ATP-dependent DNase (Epicentre); NotI (Fermentas)', 'REPLI-g Mini Kit (Qiagen)' ),
                 c('Plant DNeasy mini kit (Qiagen)', 'Geneclean kit (MPBio)',
                   'Plasmid-Safe ATP-dependent DNase, (Epicentre)', 'Illustra TempliPhi kit (GE Healthcare)'),
                 c('Plasmid Mini AX (A&A Biotechnology)', 'Plasmid Mini AX (A&A Biotechnology)', 
                   'Plasmid-Safe ATP-dependent DNase (Epicentre); MssI (Thermo Scientific)', 'REPLI-g Midi Kit (Qiagen)'),
                 c('Plant DNeasy mini kit (Qiagen)', 'Geneclean kit (MPBio)',
                   'Plasmid-Safe ATP-dependent DNase (Epicentre)', 'REPLI-g Mini Kit (Qiagen)'),
                 c('SDS and KAc extraction', 'DNA Clean and Concentrator-5 Kit (Zymo Research)',
                   'Plasmid-Safe ATP-dependent DNase (Epicentre)', 'Illustra TempliPhi kit (GE Healthcare)'),
                 c('Plant DNeasy mini kit (Qiagen)', 'DNA Clean and Concentrator-5 Kit (Zymo Research)',
                   'Plasmid-Safe ATP-dependent DNase (Epicentre)', 'Illustra TempliPhi kit (GE Healthcare)'))))


colnames(df) <- c('DNA extraction', 'Column purification', 'Linear DNA degradation', 'Circular DNA amplification')

df$rownames <- c('Moller et al 2015', 'Lanciano et al 2017', 'Moller et al 2018', 'Wang et al 2021', 'This Study (Magnaporthe oryzae)', 'This Study (Oryza sativa)')

## just table formatting

gt <- gt(df, rowname_col = 'rownames')

gt <- cols_align(gt, align = 'center', columns = everything())

gt <- cols_width(gt, everything() ~ px(150))

gt <- tab_stubhead(gt, 'Study')

gtsave(gt, 'ecc_datasets_metadata.png')

```


```{r}

## primer sequences

primer_names <- c('MagACTqPCR3-F', 'MagACTqPCR3-R',
                  'MagACT-F', 'MagACT-R', 
                  'AvrPita3_G3_1Aecc_F2', 'AvrPita3_G3_1Aecc_R2',
                  'AvrPi9_G3_1Aecc_F1', 'AvrPi9_G3_1Aecc_R1',
                  'AvrPi54_G3_1Aecc_F2','AvrPi54_G3_1Aecc_R2',
                  'AvrPiz-t_G3_1Aecc_F2', 'AvrPiz-t_G3_1Aecc_R2',
                  'Pwl4_G3_2Aecc_F2', 'Pwl4_G3_2Aecc_F2',
                  'AvrPita1_G3_1Cecc_F1', 'AvrPita1_G3_1Cecc_R1',
                  'TRF1_G3_1Aecc_F2', 'TRF1_G3_1Aecc_R2',
                  'PTP2_G3_1Cecc_F2', 'PTP2_G3_1Cecc_R2'
                  )

primer_sequences <- c(
  'GTATGTGCAAGGCCGGTTTC',
  'GCACATCTGTCGACAAACCG',
  'TGGCACCACACCTTCTACAACG',
  'CGCTCGTTGCCGATGGTGAT',
  'ACAAAGCGCGGAATCAAAGC',
  'GGTCTGTGAAGCTTGGTTCG',
  'AGGGGGTAAGCAAAGCAGAC',
  'TACATGGCGCGGGATGATAG',
  'ATGCCACGCCATGCTAATTC',
  'AGATGATGGTGGCGGTGAAC',
  'CTTCCAAATGATGCGCCACG',
  'ATGGCTGGATGGTGGAGAAG',
  'CATGGCGAAAAGTTGTTGCG',
  'CAGGTGCCCGGCTAATAAAG',
  'TTTTATATAAGGCAAGAGTTGGGC',
  'GGCCAAGCGACCCTAAAAAC',
  'CGAGATGAGCAGCAGACACG',
  'CCCCACCTACGTCTCCAAAAC',
  'CCAGTTAGTTGTTGTGCTGAGG',
  'AGGACCTTGTGATAACGGCG'
  )

df <- data.frame(primer_names, primer_sequences)

colnames(df) <- c('Primer name', 'Primer sequence')


gt <- gt(df, rowname_col = 'primer_names')

gt <- cols_align(gt, align = 'center', columns = everything())

gt <- cols_width(gt, everything() ~ px(500))

gt <- tab_stubhead(gt, 'Study')

gtsave(gt, 'primers.png')

```

