---
#MIT License
#
#Copyright (c) 2021 Pierre Michel Joubert
#
#Permission is hereby granted, free of charge, to any person obtaining a copy
#of this software and associated documentation files (the "Software"), to deal
#in the Software without restriction, including without limitation the rights
#to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
#copies of the Software, and to permit persons to whom the Software is
#furnished to do so, subject to the following conditions:
#
#The above copyright notice and this permission notice shall be included in all
#copies or substantial portions of the Software.
#
#THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
#IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
#FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
#AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
#LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
#OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
#SOFTWARE.
title: "acs_on_eccdnas_analysis_md"
output: html_document
---

```{r}
library(data.table)
library(ggplot2)
library(scales)

# read in data to df

df_large <- data.frame(fread('large_eccdnas_w_acs'))

# large eccdnas first

large_eccdnas_w_acs_count <- nrow(df_large)

# compare to permuted data

df_permute_large <- data.frame(fread('permute_large_eccs.txt'))

df_permute_large$freq <- df_permute_large$V1

# permutation dsn plot for large eccdnas

p <- ggplot(df_permute_large, aes(x=freq)) + 
  geom_histogram(color="black", fill="white",bins=100) + theme_classic() +
  geom_vline(xintercept = large_eccdnas_w_acs_count, size=1.5) + 
  xlim(large_eccdnas_w_acs_count*0.5, large_eccdnas_w_acs_count*1.1) + # fix axis to look okay
  labs(x="Regions containing ACS per permutation",
       y="Frequency")

p

ggsave("acs_on_large_eccs_permutation.pdf", plot = p, width = 6, height = 4)
```

```{r}

# permutation mean vs observed mean

observed <- large_eccdnas_w_acs_count

mean_expected <- mean(df_permute_large$freq)
  
print(observed)
print(mean_expected)

```


```{r}

# read in large eccdna split reads w and without acs and change colnames
df_large_srcount_w_acs <- data.frame(fread('large_eccdnas_w_acs_counted'))

df_large_srcount_w_acs$V5 <- rep("w_acs", nrow(df_large_srcount_w_acs))

colnames(df_large_srcount_w_acs) <- c('chrom', 'start','end','sr_count', 'acs')

df_large_srcount_w_acs$sr_count <- log10(df_large_srcount_w_acs$sr_count)
  
df_large_srcount_no_acs <- data.frame(fread('large_eccdnas_no_acs_counted'))

df_large_srcount_no_acs$V5 <- rep("no_acs", nrow(df_large_srcount_no_acs))

colnames(df_large_srcount_no_acs) <- c('chrom', 'start','end','sr_count', 'acs')

# log transform

df_large_srcount_no_acs$sr_count <- log10(df_large_srcount_no_acs$sr_count)

df_large_srcount <- rbind(df_large_srcount_w_acs, df_large_srcount_no_acs)

# plot boxplot comparison

p <- ggplot(df_large_srcount, aes(x=acs, y=sr_count))+geom_boxplot()+
  labs(x="",
       y="Log10 normalized \njunction split read count") + scale_x_discrete(labels=c("No ACS", "With ACS"))+
  theme(axis.text=element_text(size=6),axis.title=element_text(size=8) , legend.title=element_text(size=8), legend.position = 'bottom', legend.text=element_text(size=6))+
  theme_classic()

p

ggsave("acs_on_large_eccs_srcount.pdf", plot = p, width = 2, height = 2)
```

```{r}

#read in data to df

# microdnas now
df_micro <- data.frame(fread('micro_dnas_w_acs'))

micro_eccdnas_w_acs_count <- nrow(df_micro)

df_permute_micro <- data.frame(fread('permute_micro_dnas.txt'))

df_permute_micro$freq <- df_permute_micro$V1

# permutation dsn plot for micro dnas

p <- ggplot(df_permute_micro, aes(x=freq)) + 
  geom_histogram(color="black", fill="white",bins=100) + theme_classic() +
  geom_vline(xintercept = micro_eccdnas_w_acs_count, size=1.5) + 
  xlim(micro_eccdnas_w_acs_count*0.5, micro_eccdnas_w_acs_count*2) + # scale axes so we can see everything
  labs(x="Regions containing ACS per permutation",
       y="Frequency")
p

ggsave("acs_on_micro_dnas_permutation.pdf", plot = p, width = 6, height = 4)
```

```{r}

# permutation mean vs observed mean

observed <- micro_eccdnas_w_acs_count

mean_expected <- mean(df_permute_micro$freq)
  
print(observed)
print(mean_expected)

```




```{r}

# read in micro dna split reads w and without acs and change colnames

df_micro_srcount_w_acs <- data.frame(fread('micro_dnas_w_acs_counted'))

df_micro_srcount_w_acs$V5 <- rep("w_acs", nrow(df_micro_srcount_w_acs))

colnames(df_micro_srcount_w_acs) <- c('chrom', 'start','end','sr_count', 'acs')

df_micro_srcount_w_acs$sr_count <- log10(df_micro_srcount_w_acs$sr_count)

df_micro_srcount_no_acs <- data.frame(fread('micro_dnas_no_acs_counted'))

df_micro_srcount_no_acs$V5 <- rep("no_acs", nrow(df_micro_srcount_no_acs))

colnames(df_micro_srcount_no_acs) <- c('chrom', 'start','end','sr_count', 'acs')

# log transform

df_micro_srcount_no_acs$sr_count <- log10(df_micro_srcount_no_acs$sr_count)

df_micro_srcount <- rbind(df_micro_srcount_w_acs, df_micro_srcount_no_acs)

# plot boxplot comparison

p <- ggplot(df_micro_srcount, aes(x=acs, y=sr_count))+geom_boxplot()+
  labs(x="",
       y="Log10 normalized \njunction split read count") + scale_x_discrete(labels=c("No ACS", "With ACS"))+
  theme(axis.text=element_text(size=6),axis.title=element_text(size=8) , legend.title=element_text(size=8), legend.position = 'bottom', legend.text=element_text(size=6))+
  theme_classic()

p

ggsave("acs_on_micro_dnas_srcount.pdf", plot = p, width = 2, height = 2)
```

