---
#MIT License
#
#Copyright (c) 2021 Pierre Michel Joubert
#
#Permission is hereby granted, free of charge, to any person obtaining a copy
#of this software and associated documentation files (the "Software"), to deal
#in the Software without restriction, including without limitation the rights
#to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
#copies of the Software, and to permit persons to whom the Software is
#furnished to do so, subject to the following conditions:
#
#The above copyright notice and this permission notice shall be included in all
#copies or substantial portions of the Software.
#
#THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
#IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
#FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
#AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
#LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
#OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
#SOFTWARE.
title: "expression_never_v_common"
output: html_document
---

```{r}
library(data.table)
library(ggplot2)


# read in table
df <- data.frame(fread('common_v_never_expression'))

# log transform
df$V2 <- log10(df$V2)

colnames(df) <- c('gene','rpkm','common_or_never')

```

```{r}

# plot boxplot of eccdna absent vs eccdna associated

labs <- c("EccDNA-associated \ngenes", "EccDNA-absent \ngenes")

p <- ggplot(df, aes(x=common_or_never, y=rpkm)) + geom_boxplot() + theme_classic() + ylab('Log 10 RPKM') + xlab('') + scale_x_discrete(labels= labs)+
  theme(axis.text=element_text(size=6),axis.title=element_text(size=8) , legend.title=element_text(size=8), legend.position = 'bottom', legend.text=element_text(size=6))


p

ggsave("expression_never_v_common_boxplot.pdf", plot = p, width = 3, height = 2)

```

```{r}
# permutation test

# observed median
observed <- median(df$rpkm[df$common_or_never == "never" ]) - median(df$rpkm[df$common_or_never == "common" ])

permutation = replicate(10000, {
  sample_small <- df[sample(nrow(df), nrow(df[df$common_or_never == "never",]) , replace = FALSE), ] # sample the size of eccdna absent genes
  sample_large <- df[! rownames(df) %in% rownames(sample_small), ] # the rest
  median(sample_small$rpkm)-median(sample_large$rpkm)
})

p <- ggplot() + aes(permutation)+ geom_histogram(binwidth=0.01, colour="black", fill="white") + xlim(-1,1) + geom_vline(xintercept=observed)

p

p_value <- mean(permutation > observed)
p_value

```

