---
title: "coverage_plot_ggplot_effectors"
output: html_document
---

```{r}
library(data.table)
library(ggplot2)
library(RColorBrewer)
library(ggpubr)

```


```{r}

df <- data.frame(fread('guy11_fungap_out_12_28_20.bed'))

df_splitreads <- data.frame(fread('G3.normalized.splitreadspergene'))

colnames(df) <- c('CHROMOSOME', 'start', 'end', 'gene')

df$CHROMOSOME <- as.numeric(substring(df$CHROMOSOME, 11, 12))
                          
df$middle <- df$start + (df$end - df$start) * 0.5

df$splitreads <- df_splitreads$V2

df$status <- NA

df$status[df$splitreads == 0] <- 'eccDNA-absent'


n_common_genes <- floor(length(df$splitreads[df$splitreads != 0])/10)

common_genes_cutoff <- sort(df$splitreads, decreasing=TRUE)[n_common_genes]

df$status[df$splitreads >= common_genes_cutoff] <- 'eccDNA-associated'

df$status[is.na(df$status)] <- 'Other genes'

df

```



```{r}

df_chromsizes <- data.frame(fread('guy11_genome_baoetal2017.chromsizes'))

colnames(df_chromsizes) <- c('chrom', 'size')
df_chromsizes$chrom <- as.numeric(substring(df_chromsizes$chrom, 11, 12))


v <- numeric()

for (scaffold in 1:56){
  v[scaffold] <- df_chromsizes$size[df_chromsizes$chrom == scaffold]
}

x <- numeric()

for (scaffold in 1:56){
  x[scaffold] <- sum(v[1:scaffold]) - v[scaffold]
}


f <- function(g) {
 base <- as.numeric(g[5])
 scaffold <- as.numeric(g[1])
 base_total <- base + x[scaffold]
 return(base_total)
}

df$BASE_TOTAL <- apply(df, 1, f)

df$status <- factor(df$status, levels=c('eccDNA-absent', 'Other genes', 'eccDNA-associated'))

df$splitreads[df$splitreads == 0] <- 0.001

df$splitreads <- log10(df$splitreads)

```



```{r}
known_effectors_file = 'known_effectors_fungap_names'
known_effectors_table = read.table(known_effectors_file, header=FALSE, sep='\t')

grab_splitreads <- function(x) {
  return(df$splitreads[df$gene == x[2]])
}
grab_base <- function(x) {
  return(df$BASE_TOTAL[df$gene == x[2]])
}

known_effectors_table$V3 <- apply(known_effectors_table, 1, grab_splitreads)
known_effectors_table$V4 <- apply(known_effectors_table, 1, grab_base)

  
colnames(known_effectors_table) <- c('known_effector_name', 'gene', 'splitreads', 'BASE_TOTAL')



## exclude AVRPi9 bc of recent duplication
#known_effectors_table <- known_effectors_table[known_effectors_table$known_effector_name != 'AvrPi9',]

```


```{r}

effector_file <- 'guy11_effector_protein_names'

effector_genes <- read.table(effector_file, header=FALSE, sep='\t')

effector = function(x, output) {
  id = x[[4]]
  if (is.element(id, effector_genes$V1)){
    return(TRUE)
  } else{
    return(FALSE)
  }
}

df$EFFECTOR <- apply(df, 1, effector)

```

```{r}

start_subset <- 1

end_subset <- 5

end_subset_first_few <- 5

count <- end_subset - start_subset + 1

ticks <- numeric()

for (scaffold in start_subset:end_subset){
  ticks <- c(ticks, v[scaffold]*0.5 + (sum(v[start_subset:scaffold]) - v[scaffold]))
  ticks <- c(ticks, v[scaffold]*1 + (sum(v[start_subset:scaffold]) - v[scaffold]))
}

labs <- rep(start_subset:end_subset, each=2)

df_subset <- df[df$CHROMOSOME >= start_subset & df$CHROMOSOME <= end_subset,]

p1 <- ggplot() + 
  geom_point(data = df_subset[df_subset$EFFECTOR==FALSE,], aes(x=BASE_TOTAL, y=splitreads, color='Other genes'),size=0.1)+
  geom_point(data = df_subset[df_subset$EFFECTOR==TRUE,], aes(x=BASE_TOTAL, y=splitreads, color='Predicted effectors'),size=0.1) +
  geom_segment(aes(x=0, xend=(sum(v[1:1]) - v[1] + sum(v[1:end_subset_first_few])), y=log10(common_genes_cutoff), 
                   yend=log10(common_genes_cutoff)),colour='#E6AB02')+
    geom_text(data = known_effectors_table, aes(x=BASE_TOTAL, y=splitreads, label=known_effector_name), size =2) +
  scale_x_continuous(labels=labs, breaks = ticks,
                     limits = c((sum(v[1:start_subset]) - v[start_subset]),
                           sum(v[1:start_subset]) - v[start_subset] + sum(v[1:end_subset_first_few]))) + 
  theme_classic() + xlab('Scaffold') +
  ylim(0, max(df$splitreads)) +
  theme(axis.text.x = element_text(colour=c(rep(c('black','transparent'),count))))+
  theme(axis.ticks.x = element_line(colour=c(rep(c('transparent','black'),count))))+
   scale_y_continuous(breaks=-3:1, labels=c("0","0.01", "0.1", "1", "10"), limits = c(-3,1)) +
  ylab('Normalized encompassing \nsplit read count')+
  theme(axis.text=element_text(size=6),axis.title=element_text(size=8) , legend.title=element_blank(), legend.position = 'bottom', legend.text=element_text(size=6)) + guides(colour = guide_legend(override.aes = list(size=2)))+
  theme(axis.line.y = element_blank()) +
  annotate(geom = "segment", x = -Inf, xend = -Inf, y = -Inf, yend = Inf) +
  annotate(geom = "segment", x = -Inf, xend = -Inf, y =  -2.75, yend = -2.5, color = "white", size = 1) +
  scale_colour_manual(breaks = c("Other genes", "Predicted effectors"),
                      values = c("Other genes" = 'grey', "Predicted effectors" = "#006400"))


ggsave('test_effector.tiff', plot=p1, width=6.5, height=1.75, device = 'tiff', dpi = 1000)


```

```{r}

start_subset <- 6

end_subset <- 56

count <- end_subset - start_subset + 1

ticks <- numeric()

for (scaffold in start_subset:end_subset){
  if (scaffold <= 15) {
    ticks <- c(ticks, v[scaffold]*0.5 + (sum(v[start_subset:scaffold]) - v[scaffold]))
    } else if (scaffold == 20) {
      ticks <- c(ticks, v[scaffold]*0.5 + (sum(v[start_subset:scaffold]) - v[scaffold]))
    } 
  ticks <- c(ticks, v[scaffold]*1 + (sum(v[start_subset:scaffold]) - v[scaffold]))
}

ticks <- ticks + sum(v[1:end_subset_first_few])

labs <- character()

for (scaffold in start_subset:end_subset){
  if (scaffold <= 15) {
    labs <- c(labs, scaffold)
    } else if (scaffold == 20) {
      labs <- c(labs,scaffold)
    } 
  labs <- c(labs, scaffold)
}

#tick colors

tick_colors <- character()
label_colors <- character()

for (scaffold in start_subset:end_subset){
  if (scaffold <= 15) {
    tick_colors <- c(tick_colors, 'transparent', 'black')
    } else if (scaffold == 20) {
      tick_colors <- c(tick_colors, 'transparent', 'black')
    } else {
      tick_colors <- c(tick_colors, 'black')
    }
  if (scaffold <= 15) {
    label_colors <- c(label_colors, 'black', 'transparent')
    } else if (scaffold == 20) {
      label_colors <- c(label_colors, 'black', 'transparent')
    } else {
      label_colors <- c(label_colors, 'transparent')
    }
}



df_subset <- df[df$CHROMOSOME >= start_subset & df$CHROMOSOME <= end_subset,]

p2 <- ggplot() + 
  geom_point(data = df_subset[df_subset$EFFECTOR==FALSE,], aes(x=BASE_TOTAL, y=splitreads, color='Other genes'),size=0.1)+
  geom_point(data = df_subset[df_subset$EFFECTOR==TRUE,], aes(x=BASE_TOTAL, y=splitreads, color='Predicted effectors'),size=0.1) +
  geom_segment(aes(x=(sum(v[1:start_subset]) - v[start_subset]), xend=(sum(v[1:end_subset])),
                y=log10(common_genes_cutoff),
                yend=log10(common_genes_cutoff) ),colour='#E6AB02')+
      geom_text(data = known_effectors_table, aes(x=BASE_TOTAL, y=splitreads, label=known_effector_name), size =2) +
  scale_x_continuous(labels=labs, breaks = ticks,
                     limits = c((sum(v[1:start_subset]) - v[start_subset]),
                           sum(v[1:start_subset]) - v[start_subset] + sum(v[1:end_subset_first_few]))) + 
  theme_classic() + xlab('Scaffold') +
  ylim(0, max(df$splitreads)) +
  theme(axis.text.x = element_text(colour=label_colors))+
  theme(axis.ticks.x = element_line(colour=tick_colors))+
   scale_y_continuous(breaks=-3:1, labels=c("0","0.01", "0.1", "1", "10"), limits = c(-3,1)) +
  ylab('Normalized encompassing \nsplit read count')+
  theme(axis.text=element_text(size=6),axis.title=element_text(size=8) , legend.title=element_blank(), legend.position = 'bottom', legend.text=element_text(size=6))+ guides(colour = guide_legend(override.aes = list(size=2)))+
  theme(axis.line.y = element_blank()) +
  annotate(geom = "segment", x = -Inf, xend = -Inf, y = -Inf, yend = Inf) +
  annotate(geom = "segment", x = -Inf, xend = -Inf, y =  -2.75, yend = -2.5, color = "white", size = 1) +
  scale_colour_manual(breaks = c("Other genes", "Predicted effectors"),
                      values = c("Other genes" = 'grey', "Predicted effectors" = "#006400"))


# p2 <- ggplot() +
#   geom_point(data = df_subset[df_subset$status=="Other genes",], aes(x=BASE_TOTAL, y=splitreads, color='Other genes'),size=0.1)+
#   geom_point(data = df_subset[df_subset$status=="eccDNA-absent",], aes(x=BASE_TOTAL, y=splitreads, color='eccDNA-absent'),size=0.1) +
#   geom_point(data = df_subset[df_subset$status=="eccDNA-associated",], aes(x=BASE_TOTAL, y=splitreads, color='eccDNA-associated'),size=0.1) +
#   geom_segment(aes(x=(sum(v[1:start_subset]) - v[start_subset]), xend=(sum(v[1:end_subset])), 
#                 y=log10(common_genes_cutoff), 
#                 yend=log10(common_genes_cutoff) ),colour='#E6AB02')+
#   scale_x_continuous(labels=labs, breaks = ticks,
#                      limits = c((sum(v[1:start_subset]) - v[start_subset]),
#                            sum(v[1:start_subset]) - v[start_subset] + sum(v[1:end_subset_first_few]))) +
#   theme_classic() + xlab('Scaffold') +
#   ylim(0, max(df$splitreads)) +
#   theme(axis.text.x = element_text(colour=label_colors))+
#   theme(axis.ticks.x = element_line(colour=tick_colors))+
#   scale_y_continuous(breaks=-3:1, labels=c("0","0.01", "0.1", "1", "10"), limits = c(-3,1)) +
#   ylab('Normalized encompassing \nsplit read count')+
#   theme(axis.text=element_text(size=6),axis.title=element_text(size=8) , legend.title=element_blank(), legend.position = 'bottom', legend.text=element_text(size=6))+ guides(colour = guide_legend(override.aes = list(size=2)))+
#   theme(axis.line.y = element_blank()) +
#   annotate(geom = "segment", x = -Inf, xend = -Inf, y = -Inf, yend = Inf) +
#   annotate(geom = "segment", x = -Inf, xend = -Inf, y =  -2.75, yend = -2.5, color = "white", size = 1)+
#   scale_colour_manual(breaks = c("eccDNA-absent", "Other genes", "eccDNA-associated"),
#                       values = c("eccDNA-absent" = '#03254c', "Other genes" = "grey", "eccDNA-associated" = "#E6AB02"))

ggsave('test_effector2.tiff', plot=p2, width=6.5, height=1.75, device = 'tiff', dpi = 1000)


```


```{r}
both <- ggarrange(p1,p2, ncol=1, nrow=2, common.legend = TRUE, legend='bottom')

ggsave('test_effector3.tiff', plot=both, width=6.5, height=4, device = 'tiff', dpi = 1000)

ggsave('effectors_coverage_plot.pdf', plot=both, width=6.5, height=3.5, device = 'pdf')

```
