---
#MIT License
#
#Copyright (c) 2021 Pierre Michel Joubert
#
#Permission is hereby granted, free of charge, to any person obtaining a copy
#of this software and associated documentation files (the "Software"), to deal
#in the Software without restriction, including without limitation the rights
#to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
#copies of the Software, and to permit persons to whom the Software is
#furnished to do so, subject to the following conditions:
#
#The above copyright notice and this permission notice shall be included in all
#copies or substantial portions of the Software.
#
#THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
#IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
#FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
#AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
#LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
#OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
#SOFTWARE.
title: "effectors_on_eccdnas_analysis"
output: html_document
---

```{r}
library(data.table)
library(ggplot2)

# read in encompassing split reads per gene
df <- data.frame(fread('G3.normalized.splitreadspergene'))

# read in list of effectors and label them in junction split reads per gene
effector_genes <- read.table('guy11_effector_protein_names', header=FALSE, sep='\t')

effector = function(x, output) {
  id = x[[1]]
  if (is.element(id, effector_genes$V1)){
    return(TRUE)
  } else{
    return(FALSE)
  }
}

df <- df[df$V3 != 0,]

df$V3 <- log10(df$V3)

df$V4 <- apply(df, 1, effector)


colnames(df) <- c('gene','rpkm','srs', 'effector')

```

```{r}

labs <- c("Other genes", "Predicted effectors")

# boxplot of encompassing split reads for effectors and non effectors

p <- ggplot(df, aes(x=effector, y=srs)) + geom_boxplot() + theme_classic() + ylab('Normalized encompassing \nsplit read count') + xlab('') + scale_x_discrete(labels= labs)+
    scale_y_continuous(labels=c(0.01,0.1,1,10), breaks = c(-2,-1,0,1))+
  theme(axis.text=element_text(size=6),axis.title=element_text(size=8) , legend.title=element_text(size=8), legend.position = 'bottom', legend.text=element_text(size=6))


p

ggsave("effectors_on_eccdnas_boxplot.pdf", plot = p, width = 3, height = 2)


```

```{r}

## simple permutation test

# observed value
observed <- median(df$srs[df$effector == TRUE ]) - median(df$srs[df$effector == FALSE ])

# build null distribution
permutation = replicate(10000, {
  sample_small <- df[sample(nrow(df), nrow(df[df$effector == TRUE,]) , replace = FALSE), ] # sample the size of candidate effectors
  sample_large <- df[! rownames(df) %in% rownames(sample_small), ] # sample the rest
  median(sample_small$srs)-median(sample_large$srs) # get expected median
})

p <- ggplot() + aes(permutation)+ geom_histogram(binwidth=0.01, colour="black", fill="white") + xlim(-1,1) + geom_vline(xintercept=observed)

p

# p-value is number of expected more extreme than observed
p_value <- mean(permutation > observed)
p_value

```
```{r}

## length controlled version of permutation test

# read in gene lengths dataframe
df_lengths <- data.frame(fread('guy11_fungap_out_12_28_20.gene_lengths'))
colnames(df_lengths) <- c('gene', 'length')
effector_genes <- lapply(effector_genes, as.character)


df_lengths_siggenes <- df_lengths[df_lengths$gene %in% effector_genes$V1, ]

# calculate gene length density KDE function
d <- density(df_lengths_siggenes$length)
density_function <- approxfun(d)
# write probabilities
probabilities <- density_function(df_lengths$length)

## replace NAs with zeroes, these genes are larger than what would ever be expected in common genes
probabilities[is.na(probabilities)] <- 0

all_genes <- df_lengths$gene

# sample genes, with weights according to their size, according to above function
sampled_genes <- data.frame(replicate(10000, sample(all_genes, size = nrow(df_lengths_siggenes), replace = FALSE, 
                                                    prob = probabilities)))


# calculate median difference for all sampled dsns
get_median_difference <- function(x) {
  x_not <- all_genes[!all_genes %in% x]
  x_srs <- df[df$gene %in% x, ]
  x_not_srs <- df[! df$gene %in% x, ]
  return(median(x_srs$srs)-median(x_not_srs$srs))
}


x <- lapply(sampled_genes, get_median_difference)

df_x <- t(data.frame(x))

hist(df_x[,1])

# p-value is number of expected more extreme than observed
mean(df_x[,1] > observed)

p <- ggplot() + aes(df_x[,1])+ geom_histogram(binwidth=0.01, colour="black", fill="white") + xlim(-1,1) + geom_vline(xintercept=observed)

p

```

