---
#MIT License
#
#Copyright (c) 2021 Pierre Michel Joubert
#
#Permission is hereby granted, free of charge, to any person obtaining a copy
#of this software and associated documentation files (the "Software"), to deal
#in the Software without restriction, including without limitation the rights
#to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
#copies of the Software, and to permit persons to whom the Software is
#furnished to do so, subject to the following conditions:
#
#The above copyright notice and this permission notice shall be included in all
#copies or substantial portions of the Software.
#
#THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
#IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
#FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
#AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
#LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
#OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
#SOFTWARE.
title: "ltr_splitreads_correlation_final"
output: html_document
---

```{r}
library(data.table)
library(ggplot2)
library(scales)

# read in table and rename columns

df <- data.frame(fread('cov_feature_table'))

colnames(df) <- c("feature","ltr_srs", "ltr_ltr_srs", "ltr_internal_srs", "reads", "junction")

# log10 reads and splitreads

df$reads <- log10(df$reads)

df$ltr_ltr_srs <- log10(df$ltr_ltr_srs)

df$ltr_internal_srs <- log10(df$ltr_internal_srs)

# remove zeroes

df <- df[df$reads != -Inf,]


df <- df[!(grepl('LTR', df$feature) &  df$ltr_ltr_srs == -Inf),]

df <- df[!(grepl('INTERNAL', df$feature) &  df$ltr_internal_srs == -Inf),]



te_list <- list()

# keep colors consistent

te_list[[1]] <- c('copia1', 'Copia1', 'LTR', 'ltr_ltr_srs', "#E6AB02")
te_list[[2]] <- c('copia1', 'Copia1', 'INTERNAL', "ltr_internal_srs", "#E6AB02")
te_list[[3]] <- c('MAGGY', 'MAGGY', 'LTR', 'ltr_ltr_srs', "#7570B3")
te_list[[4]] <- c('MAGGY', 'MAGGY', 'INTERNAL', "ltr_internal_srs", "#7570B3")
te_list[[5]] <- c('GYMAG1', 'GYMAG1', 'LTR', 'ltr_ltr_srs', '#03254c')
te_list[[6]] <- c('GYMAG1', 'GYMAG1', 'INTERNAL', "ltr_internal_srs", '#03254c')
te_list[[7]] <- c('GYMAG2', 'GYMAG2', 'LTR', 'ltr_ltr_srs', "#2a9df4")
te_list[[8]] <- c('GYMAG2', 'GYMAG2', 'INTERNAL', "ltr_internal_srs", "#2a9df4")
te_list[[9]] <- c('MGRL3', 'MGRL3', 'LTR', 'ltr_ltr_srs', "#E7298A")
te_list[[10]] <- c('MGRL3', 'MGRL3', 'INTERNAL', "ltr_internal_srs", "#E7298A")
te_list[[11]] <- c('PYRET', 'PYRET', 'LTR', 'ltr_ltr_srs', "#66A61E")
te_list[[12]] <- c('PYRET', 'PYRET', 'INTERNAL', "ltr_internal_srs", "#66A61E")




```

```{r}

# testing specific elements
element <- 'MGRL3'

segment <- 'INTERNAL'

df_subset <- df[grepl(element, df$feature),]

df_subset <- df_subset[grepl(segment, df_subset$feature),]

log10((max(10^df_subset$reads)-min(10^df_subset$reads))/2)

(max(df_subset$reads)-min(df_subset$reads))/2

p <- ggplot(df_subset, aes_string(x='reads', y=segment_srs)) + 
  geom_point() +
  #geom_smooth(method='lm', color='red') +
  labs(x="Reads per million", y="Split reads per million") + theme_classic() + 
  labs(title=element)+#, subtitle=cor)+
  theme(axis.text=element_text(size=6), axis.title=element_text(size=8), plot.title=element_text(size=8, hjust=0.5), plot.subtitle=element_text(size=6, hjust=0.5))+
  annotate(geom = 'text', label = 'sometext', x = center, y = Inf, hjust = 0, vjust = 1)
  
  




```





```{r}

# make plots for individual tes and print out cor values

for (te in te_list) {
  element <- te[[1]]
  
  element_label <- te[[2]]
  
  segment <- te[[3]]
  
  segment_srs <- te[[4]]
  
  element_color <- te[[5]]
  
  
  df_subset <- df[grepl(element, df$feature),]

  df_subset <- df_subset[grepl(segment, df_subset$feature),]
  
  # correlation test and round for printing
  
  cor_test <- cor.test(df_subset[['reads']], df_subset[[segment_srs]], method=c("pearson"))
  cor <- round(cor_test$estimate[[1]], digits = 4)
  
  
  p <- ggplot(df_subset, aes_string(x='reads', y=segment_srs)) + 
    geom_point(size=0.5, color = element_color) +
    #geom_smooth(method='lm', color='red') +
    labs(x="Log10 reads per million", y="Log10 split reads per million") + theme_classic() + 
    labs(title=element_label, subtitle=paste('cor = ', cor, sep=''))+ # paste correlation to plot
    theme(axis.text=element_text(size=6), axis.title=element_text(size=8), plot.title=element_text(size=8, hjust=0.5), plot.subtitle=element_text(size=6, hjust=0.5))+
    theme(plot.title=element_text(face="italic"))

  
  # save correlation plots
  
  ggsave(paste(element,'_',segment,'_splitreads_correlation.pdf',sep=''), plot = p, width = (6.5/3), height = 2)
  
  print(element)
  print(segment)
  
  print(cor.test(df_subset[['reads']], df_subset[[segment_srs]], method=c("pearson")))
  
  print(summary(lm(df_subset[[segment_srs]] ~ df_subset[['reads']])))
  
}


```

