---
#MIT License
#
#Copyright (c) 2021 Pierre Michel Joubert
#
#Permission is hereby granted, free of charge, to any person obtaining a copy
#of this software and associated documentation files (the "Software"), to deal
#in the Software without restriction, including without limitation the rights
#to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
#copies of the Software, and to permit persons to whom the Software is
#furnished to do so, subject to the following conditions:
#
#The above copyright notice and this permission notice shall be included in all
#copies or substantial portions of the Software.
#
#THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
#IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
#FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
#AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
#LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
#OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
#SOFTWARE.
title: "ltr_splitreads_relative_comparison"
output: html_document
---


```{r}
library(data.table)
library(ggplot2)
library(scales)




te_list <- list()

# to keep colors consistent

te_list[[1]] <- c('copia1', "#E6AB02")
te_list[[2]] <- c('MAGGY', "#7570B3")
te_list[[3]] <- c('GYMAG1', '#03254c')
te_list[[4]] <- c('GYMAG2', "#2a9df4")
te_list[[5]] <- c('MGRL3', "#E7298A")
te_list[[6]] <- c('PYRET', "#66A61E")

samples <- c('G3_1A', 'G3_1B', 'G3_1C', 'G3_2A', 'G3_2B', 'G3_2C', 'G3_3A', 'G3_3B') 

```


```{r}

# define empty dataframes to add data to

columns= c("element","sample","normalized_ltr_ltr_srs") 
df_ltr_ltr_srs_final = data.frame(matrix(nrow = 0, ncol = length(columns))) 
colnames(df_ltr_ltr_srs_final) = columns

columns= c("element","sample","normalized_ltr_internal_srs") 
df_ltr_internal_srs_final = data.frame(matrix(nrow = 0, ncol = length(columns))) 
colnames(df_ltr_internal_srs_final) = columns


for (sample in samples) {

  # read in table and rename columns
  
  df <- data.frame(fread(paste(sample,'.cov_perfeature_table',sep='')))
  
  colnames(df) <- c("feature","ltr_srs", "ltr_ltr_srs", "ltr_internal_srs", "reads", "junction")

  normalized_ltr_ltr_srs_list <- list()
  
  normalized_ltr_internal_srs_list <- list()
  
  
  # get sums per TE
  for (te in te_list) {
    element <- te[[1]]
    
    df_subset <- df[grepl(element, df$feature),]
  
    sum_ltr_ltr_srs <- sum(df_subset$ltr_ltr_srs)
    
    sum_ltr_internal_srs <- sum(df_subset$ltr_internal_srs)
    
    # number of reads mapping to that element
    sum_reads <- sum(df_subset$reads)
    
    normalized_ltr_ltr_srs_list[[element]] <- c(element, sum_ltr_ltr_srs/sum_reads*1000000)
    
    normalized_ltr_internal_srs_list[[element]] <- c(element, sum_ltr_internal_srs/sum_reads*1000000)
    
  }
  
  df_normalized_ltr_ltr_srs <- data.frame(t(data.frame(normalized_ltr_ltr_srs_list)))
  
  colnames(df_normalized_ltr_ltr_srs) <- c('element','normalized_ltr_ltr_srs')
  
  df_normalized_ltr_ltr_srs$normalized_ltr_ltr_srs <- as.numeric(as.character(df_normalized_ltr_ltr_srs$normalized_ltr_ltr_srs))
  
  df_normalized_ltr_internal_srs <- data.frame(t(data.frame(normalized_ltr_internal_srs_list)))
  
  colnames(df_normalized_ltr_internal_srs) <- c('element','normalized_ltr_internal_srs')
  
  # finicky numeric issues
  df_normalized_ltr_internal_srs$normalized_ltr_internal_srs <- as.numeric(as.character(df_normalized_ltr_internal_srs$normalized_ltr_internal_srs))
  
  df_normalized_ltr_ltr_srs$element <- factor(df_normalized_ltr_ltr_srs$element, levels=c('MAGGY', 'MGRL3', 'copia1', 'GYMAG1', 'GYMAG2', 'PYRET'))
  
  df_normalized_ltr_ltr_srs$sample <- rep(sample, 6)
  
  rownames(df_normalized_ltr_ltr_srs) <- NULL
  
  # add to total dataframe
  df_ltr_ltr_srs_final <- rbind(df_ltr_ltr_srs_final, df_normalized_ltr_ltr_srs)
  
  df_normalized_ltr_internal_srs$element <- factor(df_normalized_ltr_internal_srs$element, levels=c('MAGGY', 'MGRL3', 'copia1', 'GYMAG1', 'GYMAG2', 'PYRET'))

  df_normalized_ltr_internal_srs$sample <- rep(sample, 6)
  
  
  rownames(df_normalized_ltr_internal_srs) <- NULL
  
  # add to total dataframe
  df_ltr_internal_srs_final <- rbind(df_ltr_internal_srs_final, df_normalized_ltr_internal_srs)
  
}

```

```{r}

colors <- c('copia1' = "#E6AB02",
'MAGGY' = "#7570B3",
'GYMAG1' = '#03254c',
'GYMAG2' = "#2a9df4",
'MGRL3' = "#E7298A",
'PYRET' = "#66A61E")

# boxplot for ltr_ltr splitreads

p <- ggplot(data=df_ltr_ltr_srs_final, aes(x=element, y=normalized_ltr_ltr_srs, color=element))+
  geom_boxplot(outlier.shape = NA) +
  geom_jitter(position=position_jitter(0.2)) +
  theme_classic()+
  ylab('LTR-LTR splitreads \nper million mapped reads')+
  xlab('')+
  scale_color_manual(values = colors)+
  scale_x_discrete(labels=c('MAGGY', 'MGRL3', 'Copia1', 'GYMAG1', 'GYMAG2', 'PYRET'))+
  theme(axis.text=element_text(size=6),axis.title=element_text(size=8) , legend.position = 'none')

p


ggsave('ltr_ltr_splitreads_normalized_barplot.pdf', plot = p, width = (6.5/2), height = 2)


```

```{r}

# barplot for ltr_internal splitreads

p <- ggplot(data=df_ltr_internal_srs_final, aes(x=element, y=normalized_ltr_internal_srs, color=element))+
  geom_boxplot(outlier.shape = NA) +
  geom_jitter(position=position_jitter(0.2)) +
  theme_classic()+
  ylab('LTR-LTR splitreads \nper million mapped reads')+
  xlab('')+
  scale_color_manual(values = colors)+
  scale_x_discrete(labels=c('MAGGY', 'MGRL3', 'Copia1', 'GYMAG1', 'GYMAG2', 'PYRET'))+
  theme(axis.text=element_text(size=6),axis.title=element_text(size=8) , legend.position = 'none')

p


ggsave('ltr_internal_splitreads_normalized_barplot.pdf', plot = p, width = (6.5/2), height = 2)

```

