---
#MIT License
#
#Copyright (c) 2021 Pierre Michel Joubert
#
#Permission is hereby granted, free of charge, to any person obtaining a copy
#of this software and associated documentation files (the "Software"), to deal
#in the Software without restriction, including without limitation the rights
#to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
#copies of the Software, and to permit persons to whom the Software is
#furnished to do so, subject to the following conditions:
#
#The above copyright notice and this permission notice shall be included in all
#copies or substantial portions of the Software.
#
#THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
#IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
#FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
#AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
#LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
#OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
#SOFTWARE.
title: "Pacbio_v_illumina_eccs"
output: html_document
---

```{r}
library(data.table)
library(ggplot2)

# read table of counts between illumina and pacbio and rename columns
df <- data.frame(fread('illumina_v_pacbio_out'))

colnames(df) <- c('sample', 'eccs_pacbio', 'eccs_pacbio_illumina_eccs_overlap', 'eccs_pacbio_illumina_splitreads_overlap')

```

```{r}

# calculate overlap percentages and make df for plotting

df$percent_illumina_eccs_overlap <- df$eccs_pacbio_illumina_eccs_overlap/df$eccs_pacbio*100
df$percent_illumina_splitreads_overlap <- df$eccs_pacbio_illumina_splitreads_overlap/df$eccs_pacbio*100

df_percent_overlap <- data.frame(
  c(rep('EccDNA forming regions', 8), rep('Split reads',8)),
  c(df$percent_illumina_eccs_overlap, df$percent_illumina_splitreads_overlap)
)

colnames(df_percent_overlap) <- c('type', 'percent')

biorep_shapes_vector <- c('circle', 'circle', 'circle', 'triangle', 'triangle', 'triangle', 'square', 'square')

biorep_shapes_vector <- factor(biorep_shapes_vector, levels = c('circle', 'triangle', 'square'))

final_shapes_vector <- rep(biorep_shapes_vector, 2)

shape_values <- c(19, 17, 15)



```


```{r}

## plot boxplot

p <- ggplot(df_percent_overlap, aes(x=type, y=percent)) + 
  geom_boxplot(outlier.shape = NA) + geom_jitter(position=position_jitter(0.2), aes(shape=final_shapes_vector))+
  scale_shape_manual(values=shape_values)+
  scale_y_continuous(limits=c(0,100.01))+ # better y axis
  ylab("Percent overlap") + xlab("") + 
    theme(axis.text=element_text(size=6), axis.title=element_text(size=8), legend.title=element_blank(), legend.position = 'none')


p

ggsave("Pacbio_v_illumina_eccs.pdf", plot = p, width = 6.5, height = 3.5)

```
```{r}

# calculate means

mean(df_percent_overlap$percent[df_percent_overlap$type == 'EccDNA forming regions'])

mean(df_percent_overlap$percent[df_percent_overlap$type == 'Split reads'])

```

